version: "3.7"
services:

#############################
# PORTALS FOR SERVER
#############################
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall
    ports:
      - "5443:443"
      - "5080:80"
    volumes:
      - ${CONFIG}/heimdall:/config
    environment:
      - PGID
      - PUID
      - TZ
    restart: unless-stopped
    networks:
      - internal
      - web

  homer:
    image: nx211/docker-homer
    container_name: homer
    hostname: homer
    ports:
      - "3443:443"
      - "3080:80"
    environment:
      - PGID
      - PUID
      - TZ
    volumes:
      - ${CONFIG}/homer/nginx:/config # optional for access to nginx config
      - ${CONFIG}/homer/config/config.yml:/homer/config.yml
    restart: unless-stopped
    networks:
      - internal
      - web

networks:
  web:
    name: web
    external: true
  internal:
    name: internal
    external: false
  db: # for containers using databases
    name: db
    external: false
