debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.dashboard]
  address = ":8080"
    [entryPoints.dashboard.auth]
    [entryPoints.dashboard.auth.basic]
      users = ["chris:{SHA}AThemvtnfYZfFZUvpu/v4jRKoU0="]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[api]
  entrypoint="dashboard"

[retry]

[acme]
email = "chris.furby@gmail.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
OnDemand = false
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  # domain = "jeebs.co"
  domain = "docker.localhost"
  watch = true
  network = "web"
