# Caddy2 reverse proxy compose file

version: "3.7"
services:

  caddy2:
    image: caddy
    container_name: caddy2
    hostname: caddy2
    # dns:
    #   - "10.0.1.3"
    #   - "1.1.1.1"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # different .env file. "CONFIG" defined as docker/caddy2
      - ${CONFIG}/config:/config
      - ${CONFIG}/data:/data
      - ${CONFIG}/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - PGID
      - PUID
      - TZ
      - DOMAIN
    restart: unless-stopped
    networks:
      - internal
      - web


networks:
  web:
    name: web
    external: true
  internal:
    name: internal
    external: false
